### ISSUE TITLE
Way to provide fontFamily or fontWeight?

### ISSUE THREAD

**Issue by ckknight** [airamrguez/react-native-measure-text#1]
As-is, this seems to only measure based on the system font.

**Comment by ayberkanilatsiz** [comment]
@ckknight https://github.com/ayberkanilatsiz/react-native-measure-text

When i add android, i will send PR

**Comment by jordanmkoncz** [comment]
Was also looking for this functionality, would be great to have it added!

**Comment by fxfactorial** [comment]
@ayberkanilatsiz Is your fork working?

**Comment by ayberkanilatsiz** [comment]
@fxfactorial it is

**Comment by fxfactorial** [comment]
@ayberkanilatsiz will you open a PR?

**Comment by ayberkanilatsiz** [comment]
@fxfactorial i did

**Comment by airamrguez** [comment]
#3

**Comment by vinh1508** [comment]
Is it support for LineHeight?

**Comment by ayberkanilatsiz** [comment]
@vinh1508 it's not support line height.

**Comment by fxfactorial** [comment]
@airamrguez it looks like the PR implementation could be a bit better.

**Comment by oferRounds** [comment]
+

**Comment by airamrguez** [comment]
Font-family has been added. It is available under the `next` tag on npm. Install it running: `yarn add react-native-measure-text@next`.

I'll add fontWeight soon.
