### ISSUE TITLE
error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by elliscwc** [airamrguez/react-native-measure-text#2]
`:react-native-measure-text:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
android\src\main\java\io\github\airamrguez\RNMeasureTextPackage.java:19: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-measure-text:compileReleaseJavaWithJavac FAILED`

@airamrguez Encountered this error when compiling in Android, I'm using React native v0.49
Thank you in advance

**Comment by elliscwc** [comment]
@airamrguez this problem might cause by the @override marker, I think remove it should do the work

**Comment by airamrguez** [comment]
Thanks @elliscwc for reporting. I've just published 1.0.0-alpha.2. This should be fixed now.
