### ISSUE TITLE
How to measure width?

### ISSUE THREAD

**Issue by Noitidart** [airamrguez/react-native-measure-text#4]
I notice this only gives me height. Is it possible to get width?

**Comment by airamrguez** [comment]
It would be cool. I can’t do this anytime soon. Of course PRs are welcome!

**Comment by airamrguez** [comment]
@Noitidart I've added width support. Could you try the new version?

**Comment by Noitidart** [comment]
Thank you very very much!!! I will try it now! :)

**Comment by Noitidart** [comment]
Having some trouble installing things. npm i is just failing super weird. I think i'll start a new proejct, for now i have to run. Thank you so much for your help!

**Comment by airamrguez** [comment]
@Notidart I'm closing this issue because this feature is already available. If you experience any issues do not hesitate on reporting them.

**Comment by Noitidart** [comment]
Thank you @airamrguez !
