### ISSUE TITLE
Just wondering what the unit of heights 

### ISSUE THREAD

**Issue by Elitebigboss90** [airamrguez/react-native-measure-text#6]
Hi,
Thank you for your work, but I am just wanna know what is the unit of the heights? DP or Pixels?

**Comment by airamrguez** [comment]
@Elitebigboss90 good question! I’ve realized that I left the transformation from px to dp on Android to be done in the react native layer. But now that you ask, I believe that this should be done in the native layer. I will review this. 
On iOS height and width are density independent pixels.

**Comment by airamrguez** [comment]
@Elitebigboss90 you shouldn't worry about units. All units (including heights) are supposed to be platform independent pixels, so they should just work. If you experience any problems do not hesitate on opening an issue with an example :-)
